### ISSUE TITLE
Occasionally I will stop being able to change input modes when away from the app 

### ISSUE THREAD

**Issue by tuchandra** [grantm/sudoku-web-app#20]
Hi, thanks again for the amazing work here. I'm not sure why this is the case, but occasionally when I'm away from the tab for some time (more than a minute probably), I'll come back to find that the zxcv shortcuts have stopped working, and that I can't click on the input mode selector to change the mode. Typing numbers still works, as does Delete (on a Mac here) but I can only enter numbers in that input mode and not switch.

**Comment by grantm** [comment]
That's a useful data point. I have seen exactly the behaviour you describe, but only in my development environment and I'd assumed it was something to do with the incremental loading of code changes. It's useful to know that it does also happen with the production build of the React app. I have no idea yet what's causing it.

**Comment by grantm** [comment]
If it happens to you again, can you check if tapping on Shift or Ctrl resets things to normal?

**Comment by grantm** [comment]
I believe I have fixed at least that known cause of the issue in release 1.0.6, but please log another issue if you experience it again.
