### ISSUE TITLE
Save progress in local storage - as protection against a crash or lost tab

### ISSUE THREAD

**Issue by grantm** [grantm/sudoku-web-app#23]
Currently the user loses all their work and has to start over if there is a crash in either the app or the user's browser. Also, on mobile, if they switch away from the browser to another app, the OS might unload either the tab or the whole browser app - and subsequently restore just the starting grid when the user returns.

Initial thoughts about how this might work:
* initialDigits and currentSnapshot saved in local storage at each step
* when page is reloaded, if initialDigits match, ask user if they wish to resume from where they left off
* this would allow user to pick up where they left off, but the undo stack would be empty after a restart
* only track one puzzle in localStorage (is complexity of tracking more than one worth the effort?)

**Comment by StasJS** [comment]
Hey Grant,

I enjoyed your NZ JSCon presentation the other week and told my partner about it. She's been having a good time using it for the past week, but would really like this feature to be added. I would be happy to play around and spike something out, if that's OK?

**Comment by grantm** [comment]
Hi Jordan. I'm sure it's a feature that many people would appreciate, so yes, have at it. It dropped off my priority list once the app got stable :-)

**Comment by grantm** [comment]
This feature is live now on SudokuExchange.com.

Thank you for both your contribution and your patience.
