### ISSUE TITLE
Clicking on edge of square removes all highlighting even when holding control

### ISSUE THREAD

**Issue by toddnguyen** [grantm/sudoku-web-app#25]
If you are highlighting squares and holding control, clicking on the edge of a square will just remove all highlights.

This is frustrating when you're clicking quickly and accidentally click and edge and remove all of the highlights that you're holding.
Maybe make it so that clicking an edge or clicking outside of the puzzle while holding control does nothing rather than resetting the highlighted squares.

**Comment by grantm** [comment]
Thanks for the report. I put in a fix for the problem you described. After I pushed up a the version I found that there are still places where you can click on a line and the selection is lost. So I'll leave this issue open and come back to it later.

**Comment by toddnguyen** [comment]
Thanks, this change is already a big improvement!

**Comment by grantm** [comment]
Should be fully fixed now.
