### ISSUE TITLE
Highlight colors in dark mode are too bright

### ISSUE THREAD

**Issue by toddnguyen** [grantm/sudoku-web-app#27]
When switching to dark mode, the highlight color remains the same as it is in light mode, so the square highlighting is too bright and also the contrast between the numbers and the squares is much lower with the light-colored numbers.

Could we have a different set of highlight colors for dark mode? Maybe the same hue and saturation but with decreased luminance would work.

**Comment by grantm** [comment]
Hi Todd. I've just pushed up a version of the Sudoku app with a revised set cell background colors for light mode and a separate set for dark mode.  Hopefully this addresses the points you raised.  Feel free to open another issue if further work is needed, but any further improvements probably need to be made by someone with a design eye - which isn't exactly one of my strengths.
