### ISSUE TITLE
Feature Request: Open Current in sudokuwiki.org Solver

### ISSUE THREAD

**Issue by ecasetracker** [grantm/sudoku-web-app#29]
Sometimes I get stump far along on a puzzle. It would be nice to see it solved from that point and avoid all the "noise" introduced in solving the easier beginning cells.

Thanks for the site. I use it nearly every day. Best I've found to do Snyder notation.

**Comment by grantm** [comment]
I'm pleased you like the site.

Your feature suggestion has been implemented and is available on the site now.

**Comment by ecasetracker** [comment]
Wow! Thanks for the quick response!
