### ISSUE TITLE
Inconsistent behaviour of Shift-Click vs Shift-Drag

### ISSUE THREAD

**Issue by grantm** [grantm/sudoku-web-app#3]
If a cell containing a digit is selected - all cells containing the same digit are highlighted.
If the user then uses Shift-Click to select or unselect additional cells, the highlighting of matched cells remains in effect.
However if the user uses Shift-Click-with-Drag to extend the selection, the highlighting of matched cells is removed.
Considerations:
* It would be better if the behaviour was consistent.
* There's an argument that having both selection highlights and matching digit highlights in effect at the same time is confusing (although this will always be the case when a single cell is clicked).
* The implementation would be simplified if the match highlighting was lost in both cases.
* Retaining the match highlighting on Shift-Click was a deliberate decision.

**Comment by plaidman** [comment]
If I can make a stuggestion, maybe add another vkbd for that, or maybe double clicking the big digits to change the highlight digit. I find when I click around to different cells and having the highlight change is distracting. And if you decouple the grid tap/drag input from the highlight function it will solve this problem and the highlight change problem.

**Comment by grantm** [comment]
But surely if you don't like the highlighting of matching digits then you would just turn that off in the settings?
This issue is about fine tuning that feature for people who have it turn on.

**Comment by plaidman** [comment]
You are right, maybe I should open a new issue for a new feature request - this one is only tangentially related to the other idea.
