### ISSUE TITLE
Feature request: option to position outer pencil marks based on value

### ISSUE THREAD

**Issue by jbchouinard** [grantm/sudoku-web-app#30]
I changed it in my fork:

[relevant commit](https://github.com/jbchouinard/sudoku-web-app/commit/1c855398c053d63a21792a8a5e0e252e1ad8cf53)
[before pic](https://raw.githubusercontent.com/jbchouinard/sudoku-web-app/positional-outer-marks/before.png)
[after pic](https://raw.githubusercontent.com/jbchouinard/sudoku-web-app/positional-outer-marks/after.png)

I think it makes it much easier to spot pointing pairs when there's overlapping marks in a box.

I placed 4 numbers in the bottom row, it's a bit weird but I wanted to leave room for an inner mark.

For sudokuexchange.com I guess you'd want to make it a setting. If there is interest I could try to look into how the settings work and do a PR.

**Comment by grantm** [comment]
You're right, it is a bit weird :-)  Your idea is an intriguing approach that I'm sure other people would find useful. I have a separate development on the go to add a "simple" pencil-marking option with the more conventional positional 3x3 layout, but that will explicitly not support inner pencil marks at the same time.
I'm going to be quite busy over the next week or so, but will give this some more thought after that.

**Comment by jbchouinard** [comment]
Yeah, it doesn't look too polished. Actually, thinking about it a bit more, I generally don't use inner and outer marks in the same cell at the same time, it looks too noisy anyway. So my only problem with 3x3 is that if there's just a 5 mark, I can't tell by looking if it's an inner or outer mark. So for me at least, 3x3 would work if inner and outer marks are different colors - to disambiguate a lone 5 mark. But I don't know how everyone else are using the marks.

(This is only a minor problem with mark autoremove, cause if I use inner marks it's always 2 or 3 numbers. I'll never write just a 5 as inner mark cause that's just solved. But autoremove could leave me with a single 5 inner mark.)

**Comment by jbchouinard** [comment]
I implemented that, I like it better:
https://github.com/jbchouinard/sudoku-web-app/commit/06f2bba13eb383ee234fd69ebc2ffaa50bd72fbf

It's just a suggestion, I will probably keep using my fork anyway as there's other changes I want to do that won't be suitable for the public site.
