### ISSUE TITLE
Cmd-W hijacked by controls in Safari browser

### ISSUE THREAD

**Issue by guiltyvictim** [grantm/sudoku-web-app#32]
Noticed that you can use the WASD keys to navigate around with keyboard, but seems to have the side-effect of hijacking the Cmd-W keyboard shortcut to close the tab.

Interestingly this does not affect Chrome, also running on MacOS.

**Comment by grantm** [comment]
Sorry about the slow response.
The new version of the software (up on the site now) should fix this problem - let me know if it doesn't (I don't have access to a MacOS machine).
