### ISSUE TITLE
Enhancement: Supply solution string for quick sanity check.

### ISSUE THREAD

**Issue by jtmcdole** [grantm/sudoku-web-app#35]
_Problem:_ I want to sanity check a single cell.

I have a list of puzzles from say, the NYT and LATimes, with solutions. These are in a spreadsheet for me to solve when I have time.

If I want a hint on just the cell I'm on, I cannot do that today.  I can:

1. Use the solution website; which is nice for when I'm stuck on the puzzle as a whole, but might go down a different path.
2. Use the solution url and quickly tab between the puzzle and the solution; trying to not peek at the unsolved cells.

Solution: Add a new `solutionDigits` from the url and track them in the grid.  Now, we wouldn't want to put the naked solution on the URL because you can see the numbers.  Instead we could do some basic obfuscation like:

```
btoa(JSON.stringify({"solution": "793618245256974138418235976972861354631549782845327691587196423364752819129483567"}))
```

Producing a url I could share with someone:
```
https://sudokuexchange.com/play/?s=090000040000070000018235970070801050600000002005000600500090003060752010000000000&pz=eyJzb2x1dGlvbiI6Ijc5MzYxODI0NTI1Njk3NDEzODQxODIzNTk3Njk3Mjg2MTM1NDYzMTU0OTc4Mjg0NTMyNzY5MTU4NzE5NjQyMzM2NDc1MjgxOTEyOTQ4MzU2NyJ9
```

Once unpacked, and stored next to each cell, it could be revealed with a UI element.

**Comment by grantm** [comment]
Sorry for leaving you hanging so long. I would question the value of being able to get the value of a specific cell with no explanation of how you could have worked it out for yourself. Even if I did want to go down that path, there's no need to pass in the solution as the solver finds the solution when the puzzle is loaded.
I'm actually currently working on a "proper" hint system that explains what the next move would be and why.

**Comment by jtmcdole** [comment]
Sounds good. This was more to match a feature on the NYT which lets you "reveal" a single digit or all placed digits.  If you have a full solve, then the same sanity check (rather than a 'hint' of what to do next') is just as easily created.
