### ISSUE TITLE
Bookmarklet for SudokuSolverNL => CTC

### ISSUE THREAD

**Issue by killroy42** [grantm/sudoku-web-app#36]
Hi Grant,

Here is one for your bookmarklets page:

Go to the twitter bot https://twitter.com/SudokuSolverNL which posts new puzzles every hour, click the link and then the bookmarklet to play that puzzle inside the CTC client.
This supports classic, windoku, x-sudoku, and windoku + x-sudoku

javascript:(function()%7B((%7Bpuzzle%3Ap%2Cvariant%3Av%7D)%3D>location.href%3D'%2F%2Ftest.crackingthecryptic.com%2Fsudoku%2Fscf'%2B(p%3D>p.replace(%2F%5Cd0%7B0%2C5%7D%2Fg%2Ci%3D>(i%3D%2Bi%5B0%5D%2B10*i.length-10%2Ci<10%3Fi%3AString.fromCharCode(i%2B(i<36%3F55%3A61)))))(p)%2B(%7Bxsudoku%3A'x'%2Cfoursquare%3A'w'%2Cx4square%3A'wx'%7D%5Bv%5D%7C%7C''))(angular.element(document.body).scope().queryParams)%7D)()%3B

Cheers,
Sven Neumann
(creator of the CTC web app)
https://www.twitch.tv/svencodes
https://twitter.com/svencodes1

**Comment by grantm** [comment]
Added.  It looks like this only works with the test site: test.crackingthecryptic.com

**Comment by killroy42** [comment]
Yeah, that's where features "ripen" before I move them over to production.
