### ISSUE TITLE
sudoku.com -> CTC

### ISSUE THREAD

**Issue by killroy42** [grantm/sudoku-web-app#37]
Hi Grant,

Here is another one for your bookmarklets page:
Just go to https://sudoku.com/ and click the bookmarklet to play that generated classic in the CTC webapp.

javascript:(function()%7Blocation.href%3D'%2F%2Ftest.crackingthecryptic.com%2Fsudoku%2Fclassic'%2B(p%3D>p.replace(%2F%5Cd0%7B0%2C5%7D%2Fg%2Ci%3D>(i%3D%2Bi%5B0%5D%2B10*i.length-10%2Ci<10%3Fi%3AString.fromCharCode(i%2B(i<36%3F55%3A61)))))(gameScene.cellsGroup.children.entries.map(d %3D> d.dataValue.text %7C%7C '0').join(''))%7D)()%3B

Cheers,
Sven Neumann
(creator of the CTC web app)
twitch.tv/svencodes
twitter.com/svencodes1

**Comment by grantm** [comment]
Added. This one seem to work with the main site app.crackingthecryptic.com, so I tweaked it to point their instead,
