### ISSUE TITLE
f-puzzles => octopuzzles.com

### ISSUE THREAD

**Issue by SorenHolstHansen** [grantm/sudoku-web-app#52]
Bookmarklet code:
```
javascript:s=location.href.replace(/^.*f-puzzles\.com\/\?load=/,'');void(window.open('https://www.octopuzzles.com/sudoku/fpuzzle?fpuzzle='+s,'_blank'));
```
This will take a puzzle from f-puzzles.com and open it on octopuzzles.com to play

My name is Søren Holst Hansen

**Comment by grantm** [comment]
I've added your bookmarklet to https://sudokuexchange.com/bookmarklets/f-puzzles-ctc.html

**Comment by SorenHolstHansen** [comment]
Thanks!
