### ISSUE TITLE
The API do not work

### ISSUE THREAD

**Issue by antrachhuynh** [grantm/sudoku-web-app#53]
/recently_shared
/explain
Do not work, can I have your API, thanks!

**Comment by grantm** [comment]
The "backend" for `/recently_shared` is literally just a static JSON file on disk with the Nginx config set up to add add a header: `Content-type: application/json`.

That file gets overwritten every hour by a cron job that make some random selections from the [puzzle bank files](https://github.com/grantm/sudoku-exchange-puzzle-bank).

The backend for `/explain` is considerably more complicated and isn't currently in a form that I can distribute easily sorry.
