### ISSUE TITLE
feature request: alternate way to input a new puzzle string

### ISSUE THREAD

**Issue by plaidman** [grantm/sudoku-web-app#7]
On mobile devices it can be tedious to tap the long URL, highlight the old string, and paste a new one. If there was a menu option to input a new puzzle string, that would be very convenient. This will also allow me to bookmark the site on my home screen, and it will be helpful if you decide to convert this app into a PWA.

**Comment by grantm** [comment]
Yes that is a feature I've been meaning to add for a while and it's definitely worth tracking here.

FYI: if you follow [a link with fewer than 81 digits](https://sudokuexchange.com/play/?s=00004500103000069409000005061470302035020407602010954304000006016300008070042000), you do get a box similar to what you're after.

**Comment by plaidman** [comment]
Love it! I'll bookmark that, thanks.
